.PHONY: clean All

All:
	@echo "----------Building project:[ basic_array_operations - Debug ]----------"
	@cd "insertion" && "$(MAKE)" -f  "basic_array_operations.mk"
clean:
	@echo "----------Cleaning project:[ basic_array_operations - Debug ]----------"
	@cd "insertion" && "$(MAKE)" -f  "basic_array_operations.mk" clean
