.PHONY: clean All

All:
	@echo "----------Building project:[ BST_from_preorder - Debug ]----------"
	@cd "BST_from_preorder" && "$(MAKE)" -f  "BST_from_preorder.mk"
clean:
	@echo "----------Cleaning project:[ BST_from_preorder - Debug ]----------"
	@cd "BST_from_preorder" && "$(MAKE)" -f  "BST_from_preorder.mk" clean
