.PHONY: clean All

All:
	@echo "----------Building project:[ infix_to_postfix_00 - Debug ]----------"
	@cd "infix_to_postfix_00" && "$(MAKE)" -f  "infix_to_postfix_00.mk"
clean:
	@echo "----------Cleaning project:[ infix_to_postfix_00 - Debug ]----------"
	@cd "infix_to_postfix_00" && "$(MAKE)" -f  "infix_to_postfix_00.mk" clean
