.PHONY: clean All

All:
	@echo "----------Building project:[ Height_and_count - Debug ]----------"
	@cd "Height_and_count" && "$(MAKE)" -f  "Height_and_count.mk"
clean:
	@echo "----------Cleaning project:[ Height_and_count - Debug ]----------"
	@cd "Height_and_count" && "$(MAKE)" -f  "Height_and_count.mk" clean
