.PHONY: clean All

All:
	@echo "----------Building project:[ basic_ll_operations - Debug ]----------"
	@cd "basic_ll_operations" && "$(MAKE)" -f  "basic_ll_operations.mk"
clean:
	@echo "----------Cleaning project:[ basic_ll_operations - Debug ]----------"
	@cd "basic_ll_operations" && "$(MAKE)" -f  "basic_ll_operations.mk" clean
