.PHONY: clean All

All:
	@echo "----------Building project:[ String_0 - Debug ]----------"
	@cd "String_0" && "$(MAKE)" -f  "String_0.mk"
clean:
	@echo "----------Cleaning project:[ String_0 - Debug ]----------"
	@cd "String_0" && "$(MAKE)" -f  "String_0.mk" clean
