.PHONY: clean All

All:
	@echo "----------Building project:[ rotation_AVL_Tree - Debug ]----------"
	@cd "rotation_AVL_Tree" && "$(MAKE)" -f  "rotation_AVL_Tree.mk"
clean:
	@echo "----------Cleaning project:[ rotation_AVL_Tree - Debug ]----------"
	@cd "rotation_AVL_Tree" && "$(MAKE)" -f  "rotation_AVL_Tree.mk" clean
