.PHONY: clean All

All:
	@echo "----------Building project:[ Queue_using_2_stacks - Debug ]----------"
	@cd "Queue_using_2_stacks" && "$(MAKE)" -f  "Queue_using_2_stacks.mk"
clean:
	@echo "----------Cleaning project:[ Queue_using_2_stacks - Debug ]----------"
	@cd "Queue_using_2_stacks" && "$(MAKE)" -f  "Queue_using_2_stacks.mk" clean
